### PR TITLE
Iterate on onSelectedItem in ListComboBox

### LINKED ISSUE #701: ComboBox triggers onSelectedItemChange when you open it
When you open the ComboBox's dropdown, the `onSelectedItemChange` is triggered, when it shouldn't. Also wrong, it triggers with the same already-selected item.

If you have a reasonable usage, like the one in our standalone sample's MarkdownEditor, where `onSelectedItemChange` triggers a side effect (state change), this is particularly obvious:

https://github.com/user-attachments/assets/d3cad3b9-2756-48ec-bff8-c6287d61eb26

The code is:

```kotlin
ListComboBox(
    items = comboBoxItems,
    modifier = Modifier.width(170.dp).padding(end = 2.dp),
    isEditable = false,
    maxPopupHeight = 150.dp,
    onSelectedItemChange = {
        selected = it
        onLoadMarkdown(if (selected == "Jewel readme") JewelReadme else MarkdownCatalog)
    },
    listItemContent = { item, isSelected, _, isItemHovered, isPreviewSelection ->
        SimpleListItem(
            text = item,
            state = ListItemState(isSelected, isItemHovered, isPreviewSelection),
            modifier = Modifier,
            style = JewelTheme.simpleListItemStyle,
            contentDescription = item,
        )
    },
)
```

### PR DESCRIPTION
**Pull request by hamen**
Fixes #701

20241125-1551-55 9491252-ezgif com-video-to-gif-converter

### CODE REVIEW

File: ui/src/main/kotlin/org/jetbrains/jewel/ui/component/ListComboBox.kt [hunk 1]
```diff
@@ -147,7 +144,11 @@ public fun ListComboBox(
                 modifier = Modifier.fillMaxWidth().heightIn(max = popupMaxHeight).padding(contentPadding),
                 selectionMode = SelectionMode.Single,
                 state = scrollState,
-                onSelectedIndexesChange = onSelectedIndexesChange(),
+                onSelectedIndexesChange = { selectedItemsIndexes ->
+                    if (selectedItemsIndexes.isEmpty()) return@SelectableLazyColumn
```
Comment (rock3r) [inline ui/src/main/kotlin/org/jetbrains/jewel/ui/component/ListComboBox.kt:148]: I don't know if this check is correct; doesn't it mean if the selection is somehow cleared, we don't get a callback?

**Review by rock3r — APPROVED** [review]
