### PR TITLE
Fix ListComboBox hover

### LINKED ISSUE #631: Add hover management to ListComboBox
- [x] On hover, list item change background, but the selected item stays unchanged
- [x] On hover, clicking an item selects the item and closes the popup
- [x] On hover, ⬆️⬇️ keys change the selected item (and the background as consequence), starting from the hovered item

20241015-1602-38 3789015-ezgif com-video-to-gif-converter

Relates to #627

### PR DESCRIPTION
**Pull request by hamen**
Closes #631 
Relates to #222

### CODE REVIEW

File: ui/src/main/kotlin/org/jetbrains/jewel/ui/component/ListComboBox.kt [hunk 1]
```diff
@@ -124,6 +129,8 @@ public fun ListComboBox(
                                             isItemHovered = it
                                             if (isItemHovered) {
                                                 hoverItemIndex = items.indexOf(item)
+                                                lastHoveredIndex = items.indexOf(item)
```
Comment (rock3r) [inline ui/src/main/kotlin/org/jetbrains/jewel/ui/component/ListComboBox.kt:132]: Maybe I am missing something but it looks like `hoverItemIndex` and `lastHoveredIndex` always have the same value...

File: ui/src/main/kotlin/org/jetbrains/jewel/ui/component/ListComboBox.kt [hunk 2]
```diff
@@ -45,6 +47,8 @@ public fun ListComboBox(
     var selectedItem by remember { mutableIntStateOf(0) }
     var isListHovered by remember { mutableStateOf(false) }
     var hoverItemIndex by remember { mutableStateOf(-1) }
+    var lastHoveredIndex by remember { mutableStateOf(-1) }
+    var previewSelection by remember { mutableStateOf(false) }
```
Comment (rock3r) [inline ui/src/main/kotlin/org/jetbrains/jewel/ui/component/ListComboBox.kt:51]: You don't need this if you make the hovered index nullable and just set it to null when hover is not happening

File: ui/src/main/kotlin/org/jetbrains/jewel/ui/component/ListComboBox.kt [hunk 3]
```diff
@@ -45,6 +47,8 @@ public fun ListComboBox(
     var selectedItem by remember { mutableIntStateOf(0) }
     var isListHovered by remember { mutableStateOf(false) }
     var hoverItemIndex by remember { mutableStateOf(-1) }
+    var lastHoveredIndex by remember { mutableStateOf(-1) }
```
Comment (rock3r) [inline ui/src/main/kotlin/org/jetbrains/jewel/ui/component/ListComboBox.kt:50]:
```suggestion
    var hoverItemIndex by remember { mutableIntStateOf(-1) }
    var lastHoveredIndex by remember { mutableIntStateOf(-1) }
```

File: ui/src/main/kotlin/org/jetbrains/jewel/ui/component/SimpleListItem.kt [hunk 4]
```diff
@@ -55,6 +60,6 @@ public fun SimpleListItem(
 @GenerateDataFunctions
 public class ListItemState(
     public val isSelected: Boolean,
-    public val isSoftSelected: Boolean,
     public val isHovered: Boolean,
+    public val previewSelection: Boolean,
```
Comment (rock3r) [inline ui/src/main/kotlin/org/jetbrains/jewel/ui/component/SimpleListItem.kt:64]: Does this need to exist? It will be true if and only if `isHovered` is true

**Review by rock3r — APPROVED** [review]

**Comment by rock3r** [comment]
Good to ship behaviour-wise, waiting for the comments and conflicts to be addressed

File: ui/src/main/kotlin/org/jetbrains/jewel/ui/component/ListComboBox.kt (hunk 2 above)
Comment (hamen) [reply ui/src/main/kotlin/org/jetbrains/jewel/ui/component/ListComboBox.kt:53]: `hoverItemIndex` is now nullable
