### PR TITLE
Fix #254 - SelectableLazyColumn multi selection bug

### LINKED ISSUE #254: SelectableLazyColumn selection mode did not work as epected
SelectableLazyColumn on SelectionMode.Single did not work as expected for cmd(or ctrl)+click 

how to reproduce:
set SelectionMode.Single on Standalone sample, then cmd+click on two different items, we have both the items selected.

### PR DESCRIPTION
**Pull request by fscarponi**
SelectableLazyColumn on SelectionMode.Single was not working as expected for cmd(or ctrl)+click
(check #254 for more details about)

### CODE REVIEW

File: foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/tree/KeyActions.kt [hunk 1]
```diff
@@ -99,13 +100,23 @@ public open class DefaultSelectableLazyColumnEventAction : PointerEventActions {
...
+        when (selectionMode) {
+            SelectionMode.None -> return
+            SelectionMode.Single -> {
+                selectableLazyListState.selectedKeys = listOf(key)
+            }
+
+            SelectionMode.Multiple -> {
+                if (selectableLazyListState.selectedKeys.contains(key)) {
+                    selectableLazyListState.selectedKeys =
+                        selectableLazyListState.selectedKeys.toMutableList().also { it.remove(key) }
```
Comment (rock3r) [inline foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/tree/KeyActions.kt:114]: Wouldn't this break when #251 ships? It's a set in there.

File: foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/tree/KeyActions.kt [hunk 2]
```diff
@@ -99,13 +100,23 @@ public open class DefaultSelectableLazyColumnEventAction : PointerEventActions {
...
-        if (selectableLazyListState.selectedKeys.contains(key)) {
-            selectableLazyListState.selectedKeys =
-                selectableLazyListState.selectedKeys.toMutableList().also { it.remove(key) }
-        } else {
-            selectableLazyListState.selectedKeys =
-                selectableLazyListState.selectedKeys.toMutableList().also { it.add(key) }
+        when (selectionMode) {
+            SelectionMode.None -> return
+            SelectionMode.Single -> {
+                selectableLazyListState.selectedKeys = listOf(key)
```
[the remark this answers is not in the document]
Comment (rock3r) [reply foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/tree/KeyActions.kt:108]: Do you know you can directly suggest these small tweaks?

image

File: foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/tree/KeyActions.kt (hunk 1 above)
Comment (fscarponi) [reply foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/tree/KeyActions.kt]: updated

**Review by rock3r — APPROVED** [review]
