### PR TITLE
Fix tooltip styling

### LINKED ISSUE #155: Fix tooltip styling
Tooltips were introduced in #154, but the styling is wrong. Compared to Swing:

 Theme (New UI) | Swing | Jewel
 --- | --- | ---
 Dark |  | image
 Light | image | image
 Light (light header) | image | image

- Border is wrong
- Content color is wrong
- Padding is wrong
- Corner radius is wrong
- Shadow is missing

### PR DESCRIPTION
**Pull request by edivad1999**
Theme (New UI) | Swing | Jewel
 --- | --- | ---
 Dark | image | image 
Light | image | image
Light (light header) | image | image

Now they look the same to me 

Fixes #155

### CODE REVIEW

File: ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/IntUiBridge.kt [hunk 1]
```diff
@@ -899,19 +899,16 @@ private fun readCircularProgressStyle(
...
-private fun readTooltipStyle(
-    isDark: Boolean,
-): IntUiTooltipStyle {
-    val background =
-        if (isDark) "Tooltip.background" else "ToolTip.background"
-    val content =
-        if (isDark) "Tooltip.foreground" else "ToolTip.foreground"
+private fun readTooltipStyle(): IntUiTooltipStyle {
+    val background = "ToolTip.background"
+    val content = "ToolTip.foreground"
```
Comment (rock3r) [inline ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/IntUiBridge.kt:904]: Plz inline these

**Review by rock3r — APPROVED** [review]
