### PR TITLE
Fix icon don't be scaled after density changed

### LINKED ISSUE #236: Icons do not scale dynamically in IDE
See [here](https://github.com/JetBrains/jewel/issues/217#issuecomment-1787645809). 

Icons do scale when you recompose them tho.

### PR DESCRIPTION
**Pull request by devkanro**
截屏2023-11-02 11 19 14

Close #236 and resolve comments in #234

### CODE REVIEW

File: ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/BridgeUtils.kt [hunk 1]
```diff
@@ -222,13 +221,9 @@ internal operator fun TextUnit.plus(delta: Float): TextUnit =
         else -> this
     }
 
-internal fun retrieveDensity(): Density {
+internal fun retrieveIdeaDensity(sourceDensity: Density): Density {
```
Comment (devkanro) [inline ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/BridgeUtils.kt:224]: The component can't be passed here when used in `SwingBridgeService`, so I moved the density calcing out of `SwingBridgeService`.

But I found we call `retrieveIdeaDensity` in composable function, so I change to use the `LocalDensity.current`.

File: ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/SwingBridgeService.kt [hunk 2]
```diff
@@ -42,14 +41,12 @@ internal class SwingBridgeService(scope: CoroutineScope) {
         return BridgeThemeData(
             themeDefinition = createBridgeThemeDefinition(),
             componentStyling = createBridgeComponentStyling(themeDefinition),
-            density = retrieveDensity(),
```
Comment (devkanro) [inline ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/SwingBridgeService.kt:45]: We can't calc the density in `SwingBridgeService` context, I move out it

File: ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+import androidx.compose.runtime.CompositionLocalProvider
+import androidx.compose.runtime.ProvidableCompositionLocal
+import androidx.compose.runtime.staticCompositionLocalOf
+import androidx.compose.ui.awt.ComposePanel
+import org.jetbrains.jewel.bridge.actionSystem.ComponentDataProviderBridge
+import org.jetbrains.jewel.bridge.theme.SwingBridgeTheme
+import org.jetbrains.jewel.foundation.ExperimentalJewelApi
+import javax.swing.JComponent
+
+public fun JewelComposePanel(
```
Comment (devkanro) [inline ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt:13]: I found the `com.intellij.platform.compose.JBComposePanel` in platform codes, but I think we need provide it in Jewel, so I create one with default theme, and other settings.

File: ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+    }
+}
+
+public interface ComposePanelScope {
+
+    public val panel: JComponent
+}
+
+@ExperimentalJewelApi
+public val LocalComponent: ProvidableCompositionLocal<JComponent> = staticCompositionLocalOf {
```
Comment (devkanro) [inline ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt:39]: It copied from `com.intellij.platform.compose.JBComposePanel`.

Maybe it won't be used(we provided it in scope), or we will remove it in next release, so I add `@ExperimentalJewelApi` annotation for it.

File: ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt [hunk 5]
```diff
@@ -84,7 +84,7 @@ public class ResourcePainterProvider(
         currentHintsProvider.hints(basePath)
             .forEach { scope.resolveHint(it) }
 
-        val cacheKey = scope.acceptedHints.hashCode()
+        val cacheKey = scope.acceptedHints.hashCode() * 31 + LocalDensity.current.hashCode()
```
Comment (devkanro) [inline ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt:87]: The key of bug #236

File: ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt (hunk 3 above)
Comment (rock3r) [reply ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt:13]: Note that Compose/Jewel-related code will be removed from 23.3 (and added back for 24.1) so `JBComposePanel` might not exist until then anyway. When it does exist, though, we should use the platform one.

File: ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt (hunk 4 above)
Comment (rock3r) [reply ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt:39]: I think we can omit it, since we don't use it. I prefer the scope, too

**Review by rock3r — APPROVED** [review]

**Comment by rock3r** [comment]
Leaving to @Walingar to ship

File: ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt (hunk 3 above)
Comment (devkanro) [reply ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt:13]: @rock3r I think the platform should not provide `JBComposePanel`, it should be provided by Jewel...

Comment (rock3r) [reply ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt:13]: It will eventually be a moot distinction :)

File: ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt (hunk 5 above)
Comment (Walingar) [inline ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt:87]: Let's then use `density` local variable here

Comment (Walingar) [reply ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt:87]: Let's surround it with remember(density, scope.acceptedHints)

File: ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+                    ComponentDataProviderBridge(this@apply) {
+                        scope.content()
+                    }
+                }
+            }
+        }
+    }
+}
+
+public interface ComposePanelScope {
```
Comment (Walingar) [inline ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt:33]: Why do we need this scope? Let's use LocalComponent composition local and use it for retrieveIdeaDensity

**Review by Walingar — CHANGES_REQUESTED** [review]

File: ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt (hunk 5 above)
Comment (devkanro) [reply ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt:87]: Using remember may be more expensive. Calculating hashcode is not an expensive operation, which is why I didn't use remember before.

File: ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt (hunk 6 above)
Comment (devkanro) [reply ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt:33]: This is just to make the JewelComposePanel DSL more powerful

Comment (Walingar) [reply ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt:33]: I'd suggest having either scope either LocalComponent, preferrably LocalComponent

Comment (rock3r) [reply ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt:33]: I see the reasoning. Hadn't considered that. Let's only keep the composition local then, since we don't need the scope anymore.

**Review by Walingar — APPROVED** [review]
